### ISSUE TITLE
FTP error

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/alimentazione_DBmeteo#1]
Il processo FTP all'interno del container entra in pausa per motivi non precisati.
L'errore identificato riguarda la funzione di C connessa alla gestione del socket FTP, ma non è chiaro quale sia la causa effettiva.
```
ftp: setsockopt: Bad file descriptor
```
Il comando lanciato prevede la modalità di debug ma non il timeout
```
ftp -n -v -d 
```
Soluzioni proposte:

1. aggiungere timeout (pare non possibile nel comando)
2. cambiare da **ftp** a **ncftp**

**Comment by msalvati** [comment]
risolto molto tempo fa con ncftp
